### ISSUE TITLE
Make udp optionals

### ISSUE THREAD

**Issue by soullivaneuh** [Algatux/influxdb-bundle#36]
Currently, both http and upd client/database instances are created, even if we don't needed.

Maybe we could make it optional with the config:

``` yaml
influx_db:
    connections:
        telegraf:
            host: '%influxdb_host%'
            database: '%influxdb_telegraf_db%'
            udp: false # Disable UDP
```

Both `udp` and `http` port would be `false` by default and a configuration validation could check if at least one of them is enabled.

Edit: Only udp will be optional: https://github.com/Algatux/influxdb-bundle/issues/36#issuecomment-223899498

What do you think?
