### ISSUE TITLE
Support a DSN for connections

### ISSUE THREAD

**Issue by dkarlovi** [Algatux/influxdb-bundle#83]
If using this bundle with Symfony Flex, the established approach is to support a [DSN for connection strings](https://en.wikipedia.org/wiki/Data_source_name) instead of having each individual part be separate, as is currently the case.

This allow to pass the connection string as one variable instead of several (up to 5) which significantly simplifies secrets management for containerized apps, you just put the entire DSN in the secret.

Here's an example usage by Doctrine Bundle in a Symfony Flex recipe:
https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml#L18

**Comment by Algatux** [comment]
@dkarlovi this can be a good idea and an improvement.

**Comment by dkarlovi** [comment]
@Algatux I think so too.

You could have something like:

```yaml
influx_db:
    connections:
        udp_conn:
            url: influxdb+udp://user:password@host:4444/database
        http_conn:
            url: influxdb+http://user:password@host:8086/database
```

Maybe the `influxdb` prefix is not even needed, what do you think?
